#!/bin/bash

prime_factors()
{
	local num=$1
	local factors=()

	for((divisor=2; divisor<=num; divisor++));do
		while ((num % divisor == 0)); do
		factors+=("$divisor")
		num=$((num / divisor))
		done
	done

	echo "$1=${factors[*]}";
}

if [ $# -ne 1 ]; then
	echo 'Usage: factors <file>'
	exit 1
fi

input_file=$1

while IFS= read -r num;do
	prime_factors "$num"
done < "$input_file"


exit 0
