#!/usr/bin/env bash

check_factor()
{
    local num1 num2
    if [ $# -ne 3 ]; then
        local args=("$@")
        num2=1
        for ((count = 2; count < ${#args[@]}; count++)); do
		((num2 *= args[count]))
        done
    else
        num2=$3
    fi

    num1=$2
    num=$(tr ':' '=' <<< "$1")

    num2=${num2#-}
    num1=${num1#-}

    if ((num2 < 0)); then
	    num2=$(( -num2 ))
	    num1=$(( -num1 ))
    fi

    if ((num2 > num1)); then
	    local temp=$num1
	    num1=$num2
	    num2=$temp
    fi

    if ((num2 == 1));then
	    echo "$num$num1"
    else
	    echo "$num$num1*$num2"
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

while read -r i; do
    result=$(factor "$i")
    check_factor $result
done < "$1"
